export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const REQUEST_CATEGORIES = "REQUEST_CATEGORIES";
export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";

export const REQUEST_POSTS = "REQUEST_POSTS";
export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const REQUEST_POST = "REQUEST_POST";
export const RECEIVE_POST = "RECEIVE_POST";
export const VOTE_POST = "VOTE_POST";
export const DELETE_POST = "DELETE_POST";

export const SORT_POSTS_BY = "SORT_POSTS_BY";

export const REQUEST_COMMENTS = "REQUEST_COMMENTS";
export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";
export const REQUEST_COMMENT = "REQUEST_COMMENT";
export const RECEIVE_COMMENT = "RECEIVE_COMMENT";
export const VOTE_COMMENT = "VOTE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const EDIT_POST = "EDIT_POST";
export const NEW_POST = "NEW_POST";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const NEW_COMMENT = "NEW_COMMENT";
